AWSTemplateFormatVersion: '2010-09-09'
Metadata: 
  License: Apache-2.0
Description: 'Example data science environment creating a new SageMaker Notebook Instance using an existing VPC.  This template also includes the creation of an Amazon S3 Bucket and IAM Role.  A lifecycle policy is also included to pull the dataset that will be used in future book chapters.'
Parameters: #These are configuration parameters that are passed in as input on stack creation
  NotebookInstanceName:
    AllowedPattern: '[A-Za-z0-9-]{1,63}'
    ConstraintDescription: Maximum of 63 alphanumeric characters. Can include hyphens but not spaces. 
    Description: SageMaker Notebook instance name
    MaxLength: '63'
    MinLength: '1'
    Type: String
    Default: 'myNotebook'
  NotebookInstanceType:
    AllowedValues:
      - ml.t2.large
      - ml.t2.xlarge
      - ml.t3.large
      - ml.t3.xlarge
    ConstraintDescription: Must select a valid notebook instance type.
    Default: ml.t3.large
    Description: Select Instance type for the SageMaker Notebook
    Type: String
  VPCSubnetIds:
    Description: The ID of the subnet in a VPC
    Type: String
    Default: 'Replace with your VPC subnet'
  VPCSecurityGroupIds:
    Description: The VPC security group IDs, in the form sg-xxxxxxxx.  
    Type: CommaDelimitedList
    Default: 'Replace with the security group id(s) for your VPC'
  KMSKeyId:
    Description: The ARN of the KMS Key to use for encrypting storage attached to notebook
    Type: String
    Default: 'Replace with your KMS Key ARN'
  NotebookVolumeSize:
    Description:  The size of the ML Storage Volume attached to your notebook instance. 
    Type: Number
    Default: 75
Resources:
  SageMakerRole: 
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "sagemaker.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonSageMakerFullAccess"
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        - "arn:aws:iam::aws:policy/IAMReadOnlyAccess"
        - "arn:aws:iam::aws:policy/AWSGlueConsoleFullAccess"
        - "arn:aws:iam::aws:policy/AWSLambda_FullAccess"
        - "arn:aws:iam::aws:policy/AmazonCognitoPowerUser"
  SageMakerLifecycleConfig:      
    Type: AWS::SageMaker::NotebookInstanceLifecycleConfig
    Properties: 
      OnCreate: 
        - Content:
            Fn::Base64: !Sub "nohup aws s3 cp s3://openaq-fetches/ s3://${S3Bucket}/data/ --recursive &"
    DependsOn: S3Bucket
  SageMakerNotebookInstance:
    Type: "AWS::SageMaker::NotebookInstance"
    Properties:
      KmsKeyId: !Ref KMSKeyId
      NotebookInstanceName: !Ref NotebookInstanceName
      InstanceType: !Ref NotebookInstanceType 
      RoleArn: !GetAtt SageMakerRole.Arn
      SubnetId: !Ref VPCSubnetIds
      SecurityGroupIds: !Ref VPCSecurityGroupIds
      LifecycleConfigName: !GetAtt SageMakerLifecycleConfig.NotebookInstanceLifecycleConfigName
      VolumeSizeInGB: !Ref NotebookVolumeSize
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: 
        Fn::Join:
          - '-'
          - - datascience-environment-notebookinstance-
            - Fn::Select:
                - 4
                - Fn::Split:
                    - '-'
                    - Fn::Select:
                        - 2
                        - Fn::Split:
                            - /
                            - Ref: AWS::StackId

Outputs:
  SageMakerNoteBookURL:
    Description: "URL for the SageMaker Notebook Instance"
    Value: !Sub 'https://${AWS::Region}.console.aws.amazon.com/sagemaker/home?region=${AWS::Region}#/notebook-instances/openNotebook/${NotebookInstanceName}'
  SageMakerNotebookInstanceARN:
    Description: "ARN for the SageMaker Notebook Instance"
    Value: !Ref SageMakerNotebookInstance
  S3BucketARN:
    Description: "ARN for the S3 Bucket"
    Value: !Ref S3Bucket

